#!/bin/bash
while true
do
echo -e "\033[31m"
cat << "EOF"
 _   _      _ _
| | | |    | | |
| |_| | ___| | | ___
|  _  |/ _ \ | |/ _ \
| | | |  __/ | | (_) |
\_| |_/\___|_|_|\___/
                 _                _     _ _
     /\         (_)              | |   | | |
    /  \   _ __  _ _ __ _   _  __| | __| | |__
   / /\ \ | '_ \| | '__| | | |/ _` |/ _` | '_ \
  / ____ \| | | | | |  | |_| | (_| | (_| | | | |
 /_/    \_\_| |_|_|_|   \__,_|\__,_|\__,_|_| |_|

<<=====>>WELCOM TO OUR HACKING GROUP<<=====>>
EOF
echo -e "\033[0m"
echo -e "\033[32m<<=====>>YOUTUBE ORIGNAL VIDEO DOWNLOADER<<=====>>\033[0m"
read -p "Enter YouTube video link: " link

yt-dlp -o "/sdcard/Download/%(title)s.%(ext)s" "$link"

if [[ $? -eq 0 ]]; then
  echo -e "\033[32mVideo downloaded successfully.\033[0m"
else
  echo -e "\033[31mError downloading video.\033[0m"
fi
sleep 2

done
